name: Build and Test
on: [push, pull_request] # replace with array '[push, pull_request]' to trigger the action on each push and pull request

env:
  working-dir: src
  test-settings: TeleScope.MSTest/github.runsettings

jobs:
  build:
    defaults:
      run:
        working-directory: ${{env.working-dir}}
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --settings ${{env.test-settings}} --verbosity normal
